name = "theui-dev"
account_id = "74c0c0beae6fa8f113955e4a18cc258f"
main = "./.cloudflare/worker.js"
compatibility_date = "2025-05-25"

[assets]
directory = ".cloudflare/public"
binding = "STATIC_ASSETS"

# Specify Node.js version for Cloudflare Pages
[build]
command = "npm run build"

[env.production.vars]
NODE_VERSION = "18.18.0"