name = "theui-dev"
account_id = "74c0c0beae6fa8f113955e4a18cc258f"
main = "./.cloudflare/worker.js"
compatibility_date = "2025-03-14"

[site]
bucket = "./.cloudflare/public"

[build]
command = "npm run build"